# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 185c385015fb7371b4eb111e32a9c5480335691d97e1e609e1ba1114c9f23a2f01d398514a952c909affca92d7a83b495348668a593e066165a6e59271676276

test:
  secret_key_base: 6b44cafff55f5bcc7aa9b908bd2b3738680670ea7149f7eb5e8a88cb68219068617a840d76d8611319c5cd0457afd39dbe4306f5de3e723640c687fef10102d1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
